version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # path to requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct" 
    insecure-external-code-execution: "deny"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
