name: Locust Load Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-locust:
    name: Run Locust Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Locust in headless mode
        run: |
          locust -f User/app.py --headless -u 10 -r 2 --run-time 10s
